version: "3.7"

volumes:
  nhm:
    driver: local

services:
    
  base_image:
    build: 
      context: ./nhmusgs-base
      args:
        insecure: "-k"
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Base Image"
    image: nhmusgs/base
    env_file:
      - nhm.env

  data-loader:
    build:
      context: ./nhmusgs-data-loader
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Data Loader"
    image: nhmusgs/data-loader
    container_name: data-loader
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  gridmet:
    build:
      context: ./nhmusgs-gridmet
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Gridmet Query"
    image: nhmusgs/gridmet
    container_name: gridmet
    env_file:
      - nhm.env
      
  ofp:
    build:
      context: ./nhmusgs-ofp
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=OFP"
    image: nhmusgs/ofp
    container_name: ofp
    environment:
      - CBH_IDIR
      - START_DATE
      - END_DATE
      - NHM_SOURCE_DIR
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  ncf2cbh:
    build:
      context: ./nhmusgs-ncf2cbh
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=NCF2CBH"
    image: nhmusgs/ncf2cbh
    container_name: ncf2cbh
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  cbhfiller:
    build:
      context: ./nhmusgs-cbhfiller
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=CBHFILLER"
    image: nhmusgs/cbhfiller
    container_name: cbhfiller
    environment:
        - CBH_IDIR
        - CBH_ODIR
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  nhm-prms:
    build:
      context: ./nhmusgs-nhm-prms
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=PRMS"
    image: nhmusgs/nhm-prms
    container_name: nhm-prms
    environment:
      - END_TIME
      - NHM_SOURCE_DIR
      - SAVE_VARS_TO_FILE
      - START_DATE
      - START_TIME
      - RESTART_DATE
      - VAR_SAVE_FILE
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  out2ncf:
    build:
      context: ./nhmusgs-nhm-out2ncf
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=OUT 2 NCF"
    image: nhmusgs/out2ncf
    container_name: out2ncf
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  verifier:
    build:
      context: ./nhmusgs-verifier
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Verifier"
    image: nhmusgs/verifier
    container_name: verifier
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm
    command:
      - "/nhm/NHM-PRMS_CONUS_GF_1_1/"
