version: "3.7"

volumes:
  nhm:
    driver: local

services:
  model:
   build: 
      context: .
      args:
         insecure: ""
   image: nhmusgs/model
   env_file:
    - nhm.env
   volumes:
      - nhm:/nhm
