#! /bin/sh
#
# U.S. Geological Survey
#
# File - model
#
# Purpose - NHM container entry-point script.
#
# Author - Andrew Halper <ashalper@usgs.gov>
#

# if the HRU data is not on the volume yet ...
if [ ! -e /nhm/gridmetetl/nhm_hru_data_gfv11 ]; then
    echo "downloading HRU data ..."
    cd /nhm/gridmetetl
    wget --progress=bar:noscroll --waitretry=3 --retry-connrefused \
	 ${HRU_SOURCE?"not defined"}
    unzip -o ${HRU_DATA_PKG?"not defined"}
    rm $HRU_DATA_PKG
fi

# if the PRMS data is not on the volume yet ...
if [ ! -e /nhm/NHM-PRMS_CONUS_GF_1_1 ]; then
  # ... download it
  echo "downloading PRMS data ..."
  cd /nhm
  wget --progress=bar:noscroll --waitretry=3 --retry-connrefused \
       ${PRMS_SOURCE?"not defined"}
  unzip -o ${PRMS_DATA_PKG?"not defined"}
  rm $PRMS_DATA_PKG
fi

# start date is the base name of the last restart file
RESTART_DATE=`cd /nhm/NHM-PRMS_CONUS_GF_1_1/restart && \
	      ls -1 *.restart | sort | tail -1 | cut -f1 -d .`

